Switch category of extensions to AI
quarkiverse/quarkus-langchain4j pull request #704
Opened 2024-06-25 12:40 UTC by cescoffier

2024-06-25 12:41 UTC, geoand approved these changes

2024-06-25 12:50 UTC, ia3andy commented
@cescoffier I think this is the place to add it: https://github.com/quarkusio/quarkus/blob/main/devtools/bom-descriptor-json/src/main/resources/catalog-overrides.json

2024-06-25 12:53 UTC, maxandersen commented on core/runtime/src/main/resources/META-INF/quarkus-extension.yaml
> +    - "AI"
should be lower case "ai", its an ID not a name/text.

2024-06-25 12:54 UTC, maxandersen requested changes
use "ai" rather than "AI" then all matches other category ids

2024-06-25 13:02 UTC, maxandersen commented
related https://github.com/quarkusio/quarkus/pull/41425

2024-06-25 13:24 UTC, cescoffier commented
Switch to "ai" instead of "AI"

2024-06-27 15:17 UTC, geoand commented
Is there something blocking this?

2024-07-03 16:02 UTC, cescoffier commented
Nothing blocking.

2024-07-03 16:26 UTC, merged